/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_rocky_TestJni */

#ifndef _Included_cn_rocky_TestJni
#define _Included_cn_rocky_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_rocky_TestJni
 * Method:    myPrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_rocky_TestJni_myPrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
